spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.H2Dialect
  http:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

application:
  geoLocationValidation: true
  geoLocationUrl: http://ip-api.com/json/
  blockedCountryCodes: ["CN", "ES", "US"]
  blockedIsps: ["AWS", "Azure", "GCP"]